version: "3.7"

# Define services
services:
  processesapi:
    image: processesapi:latest
    network_mode: bridge
    container_name: processes-api
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - database
    links:
      - database

  database:
    image: postgres:latest
    network_mode: bridge
    container_name: processes-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=processes
    restart: unless-stopped

volumes:
  postgres-data: