version: "3.7"

# Define services
services:
  api:
    # image: processesapi:latest
    build:
      context: processesapi
      dockerfile: Dockerfile
    container_name: processes-api
    ports:
      - 8080:8080
    expose: 
      - 8080
    restart: unless-stopped
    depends_on:
      - database
    networks: 
      - backend

  database:
    image: postgres:latest
    container_name: processes-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=processes
    restart: unless-stopped
    networks: 
      - backend

networks: 
  backend:

volumes:
  postgres-data: