server:
  port: 8080

spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/processosdb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    schema: classpath:/sql/schema.sql
    data:
    - classpath:sql/data.sql
  