# Generated by Django 3.0.6 on 2020-05-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_processo', models.CharField(max_length=30)),
                ('pendente', models.CharField(default='s', max_length=10)),
                ('finalizadores', models.ManyToManyField(related_name='processos', to=settings.AUTH_USER_MODEL, verbose_name='Finalizadores')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(verbose_name='Parecer')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
        ),
    ]
