# Generated by Django 3.0.6 on 2020-06-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20200601_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parecer', to='processos.Processo', verbose_name='Processo'),
        ),
    ]
