# Generated by Django 3.0.6 on 2020-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20200601_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='parecer',
            field=models.TextField(blank=True, null=True, verbose_name='parecer'),
        ),
        migrations.DeleteModel(
            name='Parecer',
        ),
    ]
