# Generated by Django 3.0.6 on 2020-06-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20200601_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
