--liquibase formatted sql

--changeset marcos.leon:003

CREATE TABLE PUBLIC.ATRIBUICOES (
    ID NUMERIC(19) NOT NULL,
    ID_PROCESSO NUMERIC(19) NOT NULL,
    ID_USUARIO_TRIADOR NUMERIC(19) NOT NULL,
    ID_USUARIO_FINALIZADOR NUMERIC(19) NOT NULL,
    DH_ATRIBUICAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_ATRIBUICOES PRIMARY KEY(ID),
    CONSTRAINT FK_ATRIBUICOES_PROCESSO FOREIGN KEY (ID_PROCESSO) REFERENCES PUBLIC.PROCESSOS (ID),
    CONSTRAINT FK_ATRIBUICOES_USUARIO_TRI FOREIGN KEY (ID_USUARIO_TRIADOR) REFERENCES PUBLIC.USUARIOS (ID),
    CONSTRAINT FK_ATRIBUICOES_USUARIO_FIN FOREIGN KEY (ID_USUARIO_FINALIZADOR) REFERENCES PUBLIC.USUARIOS (ID)
);

CREATE SEQUENCE SEQ_ATRIBUICOES START 1;

CREATE INDEX IDX_ATRIBUICOES_PROCESSO ON PUBLIC.ATRIBUICOES (ID_PROCESSO ASC);
CREATE INDEX IDX_ATRIBUICOES_USUARIO_TRI ON PUBLIC.ATRIBUICOES (ID_USUARIO_TRIADOR ASC);
CREATE INDEX IDX_ATRIBUICOES_USUARIO_FIN ON PUBLIC.ATRIBUICOES (ID_USUARIO_FINALIZADOR ASC);

--rollback DROP SEQUENCE PUBLIC.SEQ_ATRIBUICOES;
--rollback DROP TABLE PUBLIC.ATRIBUICOES CASCADE;