--liquibase formatted sql

--changeset marcos.leon:004

CREATE TABLE PARECERES (
    ID NUMERIC(19) NOT NULL,
    ID_PROCESSO NUMERIC(19) NOT NULL,
    ID_ATRIBUICAO NUMERIC(19) NOT NULL,
    ID_USUARIO_PARECER NUMERIC(19) NOT NULL,
    TEXTO_PARECER TEXT NOT NULL,
    DH_PARECER TIMESTAMP NOT NULL,
    CONSTRAINT PK_PARECERES PRIMARY KEY(ID),
    CONSTRAINT FK_PARECERES_PROCESSOS FOREIGN KEY (ID_PROCESSO) REFERENCES PUBLIC.PROCESSOS (ID),
    CONSTRAINT FK_PARECERES_ATRIBUICOES FOREIGN KEY (ID_ATRIBUICAO) REFERENCES PUBLIC.ATRIBUICOES (ID),
    CONSTRAINT FK_PARECERES_USUARIOS_PAREC FOREIGN KEY (ID_USUARIO_PARECER) REFERENCES PUBLIC.USUARIOS (ID)
);

CREATE SEQUENCE PUBLIC.SEQ_PARECERES START 1;

CREATE INDEX IDX_PARECERES_PROCESSOS ON PUBLIC.PARECERES (ID_PROCESSO ASC);
CREATE INDEX IDX_PARECERES_ATRIBUICOES ON PUBLIC.PARECERES (ID_ATRIBUICAO ASC);
CREATE INDEX IDX_PARECERES_USUARIOS_PAREC ON PUBLIC.PARECERES (ID_USUARIO_PARECER ASC);

--rollback DROP SEQUENCE PUBLIC.SEQ_PARECERES;
--rollback DROP TABLE PUBLIC.PARECERES CASCADE;