# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Listar Processos
GET http://localhost:8082/api/processos
Accept: application/json

### Filtrar Usuários
POST http://localhost:8082/api/processos/filtro?page=0&size=10&sort=
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
}


### Cadastrar Usuário
POST http://localhost:8082/api/processos
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "nome": "Teste doido",
  "cpf": null,
  "telefone": null,
  "aniversario": "1992-02-11",
  "endereco": null,
  "ativo": false,
  "login": null,
  "senha": null,
  "perfil": null
}

### Atualizar as estatísticas do Canal
PUT http://localhost:8082/api/processos
Accept: application/json
Cache-Control: no-cache

{
}