INSERT INTO roles(name)
SELECT * FROM (SELECT 'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_ADMIN'
) LIMIT 1;

INSERT INTO roles(name)
SELECT * FROM (SELECT 'ROLE_USER_SCREENER') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_USER_SCREENER'
) LIMIT 1;

INSERT INTO roles(name)
SELECT * FROM (SELECT 'ROLE_USER_FINISHER') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_USER_FINISHER'
) LIMIT 1;

