INSERT INTO roles(name)
SELECT * FROM (SELECT 'ROLE_USER') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_USER'
) LIMIT 1;


INSERT INTO roles(name)
SELECT * FROM (SELECT 'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_ADMIN'
) LIMIT 1;