CREATE SCHEMA CHL_OWNER;

-- ======================================== ROLES ========================================
CREATE TABLE CHL_OWNER.ROLES (
  ID   SMALLINT PRIMARY KEY   NOT NULL,
  NAME VARCHAR(30)            NOT NULL
);
-- DROP TABLE CHL_OWNER.ROLES;

CREATE SEQUENCE CHL_OWNER.SEQ_ROLES
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 100
  START WITH 1;
--DROP SEQUENCE CHL_OWNER.SEQ_ROLES;
