-- ======================================== ROLES ========================================
CREATE TABLE CHL_OWNER.ROLES (
  ID   SMALLINT PRIMARY KEY   NOT NULL,
  NAME VARCHAR(30)            NOT NULL
);
-- DROP TABLE CHL_OWNER.ROLES;

CREATE SEQUENCE CHL_OWNER.SEQ_ROLES
  INCREMENT BY 1
  MINVALUE 50
  MAXVALUE 100
  START WITH 50;
--DROP SEQUENCE CHL_OWNER.SEQ_ROLES;

-- ======================================== USERS ========================================

CREATE TABLE CHL_OWNER.USERS (
  ID       BIGINT PRIMARY KEY   NOT NULL,
  EMAIL    VARCHAR(100)          NOT NULL,
  PASSWORD VARCHAR(100)           NOT NULL,
  NAME     VARCHAR(100)          NOT NULL,
  ENABLED  BOOLEAN               NOT NULL,
  I_ROLES BIGINT NOT NULL ,
  CONSTRAINT FK_USERS_ROLES FOREIGN KEY (I_ROLES) REFERENCES CHL_OWNER.ROLES (ID)
);
-- DROP TABLE CHL_OWNER.USERS;

CREATE SEQUENCE CHL_OWNER.SEQ_USERS
  INCREMENT BY 1
  MINVALUE 10
  MAXVALUE 2147483647
  START WITH 10;
--DROP SEQUENCE CHL_OWNER.SEQ_USERS;

CREATE INDEX IDX_USERS_ROLES
  ON CHL_OWNER.USERS (I_ROLES);
-- DROP INDEX IDX_USERS_ROLES;

-- ======================================== OAUTH ========================================

CREATE TABLE AUTH_OWNER.OAUTH_CLIENT_DETAILS (
  CLIENT_ID               VARCHAR(255) PRIMARY KEY,
  RESOURCE_IDS            VARCHAR(255),
  CLIENT_SECRET           VARCHAR(255),
  SCOPE                   VARCHAR(255),
  AUTHORIZED_GRANT_TYPES  VARCHAR(255),
  WEB_SERVER_REDIRECT_URI VARCHAR(255),
  AUTHORITIES             VARCHAR(255),
  ACCESS_TOKEN_VALIDITY   INTEGER,
  REFRESH_TOKEN_VALIDITY  INTEGER,
  ADDITIONAL_INFORMATION  VARCHAR(4096),
  AUTOAPPROVE             VARCHAR(255)
);

CREATE TABLE AUTH_OWNER.OAUTH_CLIENT_TOKEN (
  TOKEN_ID          VARCHAR(256),
  TOKEN             BYTEA,
  AUTHENTICATION_ID VARCHAR(256),
  USER_NAME         VARCHAR(256),
  CLIENT_ID         VARCHAR(256)
);


CREATE TABLE AUTH_OWNER.OAUTH_ACCESS_TOKEN (
  TOKEN_ID          VARCHAR(256),
  TOKEN             BYTEA,
  AUTHENTICATION_ID VARCHAR(256),
  USER_NAME         VARCHAR(256),
  CLIENT_ID         VARCHAR(256),
  AUTHENTICATION    BYTEA,
  REFRESH_TOKEN     VARCHAR(256)
);

CREATE TABLE AUTH_OWNER.OAUTH_REFRESH_TOKEN (
  TOKEN_ID       VARCHAR(256),
  TOKEN          BYTEA,
  AUTHENTICATION BYTEA
);

CREATE TABLE AUTH_OWNER.OAUTH_CODE (
  CODE           VARCHAR(256),
  AUTHENTICATION BYTEA
);

CREATE TABLE AUTH_OWNER.OAUTH_APPROVALS (
  USERID         VARCHAR(256),
  CLIENTID       VARCHAR(256),
  SCOPE          VARCHAR(256),
  STATUS         VARCHAR(10),
  EXPIRESAT      TIMESTAMP,
  LASTMODIFIEDAT TIMESTAMP
);
