--liquibase formatted sql

--changeset marcos.leon:001

CREATE TABLE PUBLIC.USUARIOS (
    ID NUMERIC(19) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SENHA VARCHAR(64) NOT NULL,
    PERFIL CHAR(1) NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID)
);

CREATE SEQUENCE PUBLIC.SEQ_USUARIOS START 1;

CREATE INDEX IDX_USUARIOS_EMAIL_SENHA ON PUBLIC.USUARIOS (EMAIL ASC, SENHA ASC);

--rollback DROP SEQUENCE PUBLIC.SEQ_USUARIOS;
--rollback DROP TABLE PUBLIC.USUARIOS CASCADE;