--liquibase formatted sql

--changeset marcos.leon:002

CREATE TABLE PUBLIC.PROCESSOS (
    ID NUMERIC(19) NOT NULL,
    SUMULA VARCHAR(500) NOT NULL,
    DH_ABERTURA TIMESTAMP NOT NULL,
    ID_USUARIO_ABERTURA NUMERIC(19),
    CONSTRAINT PK_PROCESSOS PRIMARY KEY(ID),
    CONSTRAINT FK_PROCESSOS_USUARIOS_ABERT FOREIGN KEY (ID_USUARIO_ABERTURA) REFERENCES PUBLIC.USUARIOS (ID)
);

CREATE SEQUENCE PUBLIC.SEQ_PROCESSOS START 1;

CREATE INDEX IDX_PROCESSOS_USUARIO_ABERT ON PUBLIC.PROCESSOS (ID_USUARIO_ABERTURA ASC);

--rollback DROP SEQUENCE PUBLIC.SEQ_PROCESSOS;
--rollback DROP TABLE PUBLIC.PROCESSOS CASCADE;