export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_WRONG_CREDENTIALS = 'LOGIN_WRONG_CREDENTIALS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const BUSCAR_PAPEIS = 'BUSCAR_PAPEIS'

export const BUSCAR_USUARIOS = 'BUSCAR_USUARIOS'
export const BUSCAR_USUARIO = 'BUSCAR_USUARIO'
export const ATRIBUIR_USUARIO_INICIAL = 'ATRIBUIR_USUARIO_INICIAL'
export const SALVAR_USUARIO = 'SALVAR_USUARIO'
export const EXCLUIR_USUARIO = 'EXCLUIR_USUARIO'


export const BUSCAR_PROCESSOS = 'BUSCAR_PROCESSOS'
export const ATRIBUIR_PROCESSO_INICIAL = 'ATRIBUIR_PROCESSO_INICIAL'
export const SALVAR_PROCESSO = 'SALVAR_PROCESSO'

export const BUSCAR_PARECERES_PROCESSO = 'BUSCAR_PARECERES_PROCESSO'
