server:
  port: 8085
  servlet:
    context-path: /processos

logging:
  level:
    org:
      springframework: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/processos
    username: postgres
    password: postgres.85
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:migrations/db.changelog-master.xml