logging:
  level:
    springfox.documentation.*: warn
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  flyway:
    enabled: false
    out-of-order: true
  h2:
    console:
      enabled: true
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:90964ab7-bfe5-4f20-97d8-10178f188bd7}
      expire-length: 3600000      
