export const GET_ERRORS = "GET_ERRORS";
export const GET_USUARIOS = "GET_USUARIOS";
export const GET_PROCESSOS = "GET_PROCESSOS";
export const GET_USUARIO = "GET_USUARIO";
export const GET_PARECER = "GET_PARECER";
export const GET_PROCESSOS_SEM_PARECER = "GET_PROCESSOS_SEM_PARECER";
export const DELETE_USUARIO = "DELETE_USUARIO";
