import { PerfilTypes } from './perfil-types';

export enum ActionsTypes  {

  // ADMIM
  INSERT_USER   = 'INSERT_USER',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER = 'UPDATE_USER',
  VIEW_USERS = 'VIEW_USERS',

  // TRIADOR
  INSERT_PROCESSO   = 'INSERT_PROCESSO',
  REPORT_PROCESSO = 'REPORT_PROCESSO',

  // FINALIZADOR

  VIEW_PROCESSO_PENDENTE = 'VIEW_PROCESSO_PENDENTE',
  INSERT_PARECER_PROCESSO = 'INSERT_PARECER_PROCESSO'


}
