# Generated by Django 3.0.6 on 2020-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Triador', 'Triador'), ('Finalizador', 'Finalizador')], default='Administrador', max_length=50, verbose_name='Tipo de usuario'),
        ),
    ]
